name: autoscrape

on:
  workflow_dispatch:
    inputs:
      show_name:
        type: choice
        description: 'Name of show for boost report'
        required: true
        default: 'LINUX Unplugged'
        options:
          - Coder Radio
          - LINUX Unplugged
          - Self-Hosted
          - 'Office Hours 2.0'
          - Linux Action News
          - Bitcoin Dad Pod
          - Unfilter
          - This Week in Bitcoin
  schedule:
    - cron: '5 8 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v19
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: dump age key
      env:
        AGE_KEY: ${{ secrets.AGE_KEY }}
      run: echo $AGE_KEY > age_key.txt
    - name: decrypt
      run: nix-shell -p 'age' --run './decrypt.sh'
    - name: Set SHOW
      env:
      # https://evanhalley.dev/post/github-actions-workflow-with-inputs/
        DEFAULT_SHOW: :lup
      run: echo "SHOW=${{ github.event.inputs.show_name || env.DEFAULT_SHOW }}" >> $GITHUB_ENV
    - name: scrape
      run: nix-shell -p 'babashka' --run "./autoscrape.sh $SHOW" > new_boosts.md
    - name: encrypt
      run: nix-shell -p 'age' --run './encrypt.sh'
    - name: cleanup
      run: rm decrypted_secrets age_key.txt
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Updating secrets."
        file_pattern: "secrets"
    - name: Archive new boosts
      uses: actions/upload-artifact@v4
      with:
        name: boosts.md
        path: new_boosts.md
